import type { Metadata } from 'next';
import { Geist, Geist_Mono, Jersey_10_Charted } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const jersey10Charted = Jersey_10_Charted({
    variable: '--font-jersey-10-charted',
    subsets: ['latin'],
    weight: ['400'],
});

export const metadata: Metadata = {
    title: 'espresso is all you need',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${jersey10Charted.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
